import { format, parseISO } from 'date-fns';

export const DEFAULT_DATE = '0001-01-01T00:00:00Z';

export function formatDate(date: string | Date, formatStr: string) {
  if (date instanceof Date) {
    return format(date, formatStr);
  }

  return format(parseISO(date), formatStr);
}

/**
 * API module (generated by SOK) return date is null type.
 * this function target data is API module return data.
 * so this function is use null type , breaking the coding rules exceptionally.
 */
export function string2date(date?: string | null) {
  if (!date) {
    return null;
  }

  return parseISO(date);
}

/**
 * API module (generated by SOK) return date is null type.
 * this function target data is API module return data.
 * so this function is use null type , breaking the coding rules exceptionally.
 */
export function string2Time(date?: string | null) {
  if (!date) {
    return null;
  }

  return parseISO(date).getTime();
}

/**
 * Reset a specific date to its starting time.
 * Eg: 2014-30-06T09:00:00 -> 2014-30-06T00:00:00
 */
export function reset2StartHour(date: Date) {
  const resetedDate = date;
  resetedDate.setHours(0, 0, 0, 0);
  return resetedDate;
}

export function isDefaultDate(date: Date | string) {
  if (typeof date === 'string') {
    return date === DEFAULT_DATE || date.startsWith('0001-01-01');
  }

  return date.getFullYear() === 1;
}
